/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package spotifei.view;

import controller.ControllerEdicaoPlaylist;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author hburi
 */
public class Interface_editarplaylist extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interface_editarplaylist
     */
    public Interface_editarplaylist() {
        initComponents();
        c = new ControllerEdicaoPlaylist(this);
    }

    public JLabel getLbl_excplaylist() {
        return lbl_excplaylist;
    }

    public JTextField getTxt_excplaylist() {
        return txt_excplaylist;
    }

    public void setLbl_excplaylist(JLabel lbl_excplaylist) {
        this.lbl_excplaylist = lbl_excplaylist;
    }

    public void setTxt_excplaylist(JTextField txt_excplaylist) {
        this.txt_excplaylist = txt_excplaylist;
    }
    
    public JButton getBtn_add() {
        return btn_add;
    }

    public JButton getBtn_editar() {
        return btn_editar;
    }

    public JButton getBtn_exc() {
        return btn_exc;
    }

    public JLabel getLbl_addmusicaplaylist() {
        return lbl_addmusicaplaylist;
    }

    public JLabel getLbl_editplaylistnome() {
        return lbl_editplaylistnome;
    }

    public JLabel getLbl_excmusicaplaylist() {
        return lbl_excplaylist;
    }

    public JLabel getLbl_inserirmusicaplaylist2() {
        return lbl_inserirmusicaplaylist2;
    }

    public JLabel getLbl_inserirnomeplaylist() {
        return lbl_inserirnomeplaylist;
    }

    public JLabel getLbl_tituloeditar() {
        return lbl_tituloeditar;
    }

    public JTextField getTxt_addmusicaplaylist() {
        return txt_addmusicaplaylist;
    }

    public JTextField getTxt_editplaylistnome() {
        return txt_editplaylistnome;
    }

    public JTextField getTxt_excmusicaplaylist() {
        return txt_excplaylist;
    }

    public JTextField getTxt_inserirmusicaplaylist2() {
        return txt_inserirmusicaplaylist2;
    }

    public JTextField getTxt_inserirnomeplaylist() {
        return txt_inserirnomeplaylist;
    }

    public void setBtn_add(JButton btn_add) {
        this.btn_add = btn_add;
    }

    public void setBtn_editar(JButton btn_editar) {
        this.btn_editar = btn_editar;
    }

    public void setBtn_exc(JButton btn_exc) {
        this.btn_exc = btn_exc;
    }

    public void setLbl_addmusicaplaylist(JLabel lbl_addmusicaplaylist) {
        this.lbl_addmusicaplaylist = lbl_addmusicaplaylist;
    }

    public void setLbl_editplaylistnome(JLabel lbl_editplaylistnome) {
        this.lbl_editplaylistnome = lbl_editplaylistnome;
    }

    public void setLbl_excmusicaplaylist(JLabel lbl_excmusicaplaylist) {
        this.lbl_excplaylist = lbl_excmusicaplaylist;
    }

    public void setLbl_inserirmusicaplaylist2(JLabel lbl_inserirmusicaplaylist2) {
        this.lbl_inserirmusicaplaylist2 = lbl_inserirmusicaplaylist2;
    }

    public void setLbl_inserirnomeplaylist(JLabel lbl_inserirnomeplaylist) {
        this.lbl_inserirnomeplaylist = lbl_inserirnomeplaylist;
    }

    public void setLbl_tituloeditar(JLabel lbl_tituloeditar) {
        this.lbl_tituloeditar = lbl_tituloeditar;
    }

    public void setTxt_addmusicaplaylist(JTextField txt_addmusicaplaylist) {
        this.txt_addmusicaplaylist = txt_addmusicaplaylist;
    }

    public void setTxt_editplaylistnome(JTextField txt_editplaylistnome) {
        this.txt_editplaylistnome = txt_editplaylistnome;
    }

    public void setTxt_excmusicaplaylist(JTextField txt_excmusicaplaylist) {
        this.txt_excplaylist = txt_excmusicaplaylist;
    }

    public void setTxt_inserirmusicaplaylist2(JTextField txt_inserirmusicaplaylist2) {
        this.txt_inserirmusicaplaylist2 = txt_inserirmusicaplaylist2;
    }

    public void setTxt_inserirnomeplaylist(JTextField txt_inserirnomeplaylist) {
        this.txt_inserirnomeplaylist = txt_inserirnomeplaylist;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloeditar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_editplaylistnome = new javax.swing.JLabel();
        txt_editplaylistnome = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_addmusicaplaylist = new javax.swing.JLabel();
        txt_addmusicaplaylist = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_inserirnomeplaylist = new javax.swing.JLabel();
        txt_inserirnomeplaylist = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lbl_inserirmusicaplaylist2 = new javax.swing.JLabel();
        txt_inserirmusicaplaylist2 = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lbl_excplaylist = new javax.swing.JLabel();
        txt_excplaylist = new javax.swing.JTextField();
        btn_exc = new javax.swing.JButton();

        setClosable(true);

        lbl_tituloeditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tituloeditar.setText("Edite sua PlayList");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_editplaylistnome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_editplaylistnome.setText("Edite o nome da sua PlayList");

        txt_editplaylistnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_editplaylistnomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_editplaylistnome)
                .addGap(62, 62, 62)
                .addComponent(txt_editplaylistnome, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_editplaylistnome)
                    .addComponent(txt_editplaylistnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_addmusicaplaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_addmusicaplaylist.setText("Adicionar música");

        txt_addmusicaplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addmusicaplaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_addmusicaplaylist)
                .addGap(149, 149, 149)
                .addComponent(txt_addmusicaplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_addmusicaplaylist)
                    .addComponent(txt_addmusicaplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_inserirnomeplaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_inserirnomeplaylist.setText("Insira o nome da sua PlayList");

        txt_inserirnomeplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inserirnomeplaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inserirnomeplaylist)
                .addGap(62, 62, 62)
                .addComponent(txt_inserirnomeplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inserirnomeplaylist)
                    .addComponent(txt_inserirnomeplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btn_editar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_inserirmusicaplaylist2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_inserirmusicaplaylist2.setText("Insira o nome da sua PlayList");

        txt_inserirmusicaplaylist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inserirmusicaplaylist2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_inserirmusicaplaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_inserirmusicaplaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inserirmusicaplaylist2)
                    .addComponent(txt_inserirmusicaplaylist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_add.setText("Adicionar");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_excplaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_excplaylist.setText("Excluir playlist");

        txt_excplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_excplaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_excplaylist)
                .addGap(160, 160, 160)
                .addComponent(txt_excplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_excplaylist)
                    .addComponent(txt_excplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_exc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exc.setText("Excluir");
        btn_exc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_exc)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_add)
                                .addComponent(btn_editar)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(lbl_tituloeditar)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_tituloeditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exc)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_inserirnomeplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inserirnomeplaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inserirnomeplaylistActionPerformed

    private void txt_editplaylistnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_editplaylistnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_editplaylistnomeActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        c.EditNomePlaylist();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void txt_inserirmusicaplaylist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inserirmusicaplaylist2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inserirmusicaplaylist2ActionPerformed

    private void txt_addmusicaplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addmusicaplaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addmusicaplaylistActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        c.AdicionarMusica();
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_excplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_excplaylistActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_excplaylistActionPerformed

    private void btn_excActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excActionPerformed
        // TODO add your handling code here:
        c.ExcluirPlaylist();
    }//GEN-LAST:event_btn_excActionPerformed

private ControllerEdicaoPlaylist c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_exc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_addmusicaplaylist;
    private javax.swing.JLabel lbl_editplaylistnome;
    private javax.swing.JLabel lbl_excplaylist;
    private javax.swing.JLabel lbl_inserirmusicaplaylist2;
    private javax.swing.JLabel lbl_inserirnomeplaylist;
    private javax.swing.JLabel lbl_tituloeditar;
    private javax.swing.JTextField txt_addmusicaplaylist;
    private javax.swing.JTextField txt_editplaylistnome;
    private javax.swing.JTextField txt_excplaylist;
    private javax.swing.JTextField txt_inserirmusicaplaylist2;
    private javax.swing.JTextField txt_inserirnomeplaylist;
    // End of variables declaration//GEN-END:variables
}
