/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

/**
 *
 * @author hburi
 */
public class Interface_playlist extends javax.swing.JFrame {

    /**
     * Creates new form Interface_playlist
     */
    public Interface_playlist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_criarplaylist = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menu_editarplaylist = new javax.swing.JMenu();
        menuitem_editarplaylist = new javax.swing.JMenuItem();
        menu_excluirplaylist = new javax.swing.JMenu();
        menuitem_excluirplaylist = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        menu_criarplaylist.setText("Criar");
        menu_criarplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_criarplaylistActionPerformed(evt);
            }
        });

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/user_add.png"))); // NOI18N
        jMenuItem3.setText("Criar PlayList");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_criarplaylist.add(jMenuItem3);

        jMenuBar1.add(menu_criarplaylist);

        menu_editarplaylist.setText("Editar");

        menuitem_editarplaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/user_edit.png"))); // NOI18N
        menuitem_editarplaylist.setText("Editar Playlist");
        menuitem_editarplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_editarplaylistActionPerformed(evt);
            }
        });
        menu_editarplaylist.add(menuitem_editarplaylist);

        jMenuBar1.add(menu_editarplaylist);

        menu_excluirplaylist.setText("Excluir");
        menu_excluirplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_excluirplaylistActionPerformed(evt);
            }
        });

        menuitem_excluirplaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/delete.png"))); // NOI18N
        menuitem_excluirplaylist.setText("Excluir playlist");
        menuitem_excluirplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_excluirplaylistActionPerformed(evt);
            }
        });
        menu_excluirplaylist.add(menuitem_excluirplaylist);

        jMenuBar1.add(menu_excluirplaylist);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_excluirplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_excluirplaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_excluirplaylistActionPerformed

    private void menuitem_editarplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_editarplaylistActionPerformed
        // TODO add your handling code here:
        Interface_editarplaylist editarplaylist = new Interface_editarplaylist();
        jPanel1.add(editarplaylist);
        editarplaylist.setVisible(true);
        
    }//GEN-LAST:event_menuitem_editarplaylistActionPerformed

    private void menuitem_excluirplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_excluirplaylistActionPerformed
        // TODO add your handling code here:
        Interface_excluirplaylist excluirplaylist = new Interface_excluirplaylist();
        jPanel1.add(excluirplaylist);
        excluirplaylist.setVisible(true);
        
    }//GEN-LAST:event_menuitem_excluirplaylistActionPerformed

    private void menu_criarplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_criarplaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_criarplaylistActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Interface_criaplaylist criaplaylist = new Interface_criaplaylist();
        jPanel1.add(criaplaylist);
        criaplaylist.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_playlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_criarplaylist;
    private javax.swing.JMenu menu_editarplaylist;
    private javax.swing.JMenu menu_excluirplaylist;
    private javax.swing.JMenuItem menuitem_editarplaylist;
    private javax.swing.JMenuItem menuitem_excluirplaylist;
    // End of variables declaration//GEN-END:variables
}
