/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

import spotifei.model.Usuario;
import spotifei.view.Interface_cadastro;
import spotifei.view.Interface_login;
import spotifei.view.Interface_AltExc;

/**
 *
 * @author hburi
 */
public class Interface_principalMDI extends javax.swing.JFrame {

    private Usuario Aluno;

    /**
     * Creates new form Interface_principalMDI
     */
    public Interface_principalMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        DesktopPane = new javax.swing.JDesktopPane();
        lbl_entrada = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_usuariosprincipal = new javax.swing.JMenu();
        menuitem_cadastropricipal = new javax.swing.JMenuItem();
        menuitem_loginprincipal = new javax.swing.JMenuItem();
        menuitem_alterarprincipal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar6.add(jMenu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_entrada.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        lbl_entrada.setText("Bem-vindo ao Spotifei - onde o som é brabo e o galo é rei!");

        DesktopPane.setLayer(lbl_entrada, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(0, Short.MAX_VALUE))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_entrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/galo_icone_60x60.png"))); // NOI18N

        menu_usuariosprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/user_suit.png"))); // NOI18N
        menu_usuariosprincipal.setText("Usuários");

        menuitem_cadastropricipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/user_add.png"))); // NOI18N
        menuitem_cadastropricipal.setText("Cadastro");
        menuitem_cadastropricipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_cadastropricipalActionPerformed(evt);
            }
        });
        menu_usuariosprincipal.add(menuitem_cadastropricipal);

        menuitem_loginprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/user_go.png"))); // NOI18N
        menuitem_loginprincipal.setText("Login");
        menuitem_loginprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_loginprincipalActionPerformed(evt);
            }
        });
        menu_usuariosprincipal.add(menuitem_loginprincipal);

        menuitem_alterarprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/user_edit.png"))); // NOI18N
        menuitem_alterarprincipal.setText("Alterar Senha");
        menuitem_alterarprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_alterarprincipalActionPerformed(evt);
            }
        });
        menu_usuariosprincipal.add(menuitem_alterarprincipal);

        jMenuBar1.add(menu_usuariosprincipal);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_cadastropricipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_cadastropricipalActionPerformed
        // TODO add your handling code here:
        
        Interface_cadastro interface_cad = new Interface_cadastro();
        
        DesktopPane.add(interface_cad);
        interface_cad.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_menuitem_cadastropricipalActionPerformed

    private void menuitem_loginprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_loginprincipalActionPerformed
        // TODO add your handling code here:
        Interface_login interface_log = new Interface_login(this);
        DesktopPane.add(interface_log);
        interface_log.setVisible(true);
        //this.setVisible(false);
        
    }//GEN-LAST:event_menuitem_loginprincipalActionPerformed

    private void menuitem_alterarprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_alterarprincipalActionPerformed
        // TODO add your handling code here:
        Interface_AltExc interface_altexc = new Interface_AltExc(Aluno);
        DesktopPane.add(interface_altexc);
        interface_altexc.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_menuitem_alterarprincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_principalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_principalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_principalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_principalMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_principalMDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JLabel lbl_entrada;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JMenu menu_usuariosprincipal;
    private javax.swing.JMenuItem menuitem_alterarprincipal;
    private javax.swing.JMenuItem menuitem_cadastropricipal;
    private javax.swing.JMenuItem menuitem_loginprincipal;
    // End of variables declaration//GEN-END:variables
}
