/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spotifei.view;

/**
 *
 * @author hburi
 */
public class Interface_online extends javax.swing.JFrame {

    /**
     * Creates new form Interface_online
     */
    public Interface_online() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuitem_musicas = new javax.swing.JMenuItem();
        menuitem_playlist = new javax.swing.JMenuItem();
        menu_buscar = new javax.swing.JMenu();
        menuitem_buscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Biblioteca");

        menuitem_musicas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/ipod_sound.png"))); // NOI18N
        menuitem_musicas.setText("Minhas Musicas");
        menuitem_musicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_musicasActionPerformed(evt);
            }
        });
        jMenu5.add(menuitem_musicas);

        menuitem_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/ipod_sound.png"))); // NOI18N
        menuitem_playlist.setText("Playlist");
        menuitem_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_playlistActionPerformed(evt);
            }
        });
        jMenu5.add(menuitem_playlist);

        jMenuBar1.add(jMenu5);

        menu_buscar.setText("Buscar");

        menuitem_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spotifei/image/zoom.png"))); // NOI18N
        menuitem_buscar.setText("Buscar musicas");
        menuitem_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_buscarActionPerformed(evt);
            }
        });
        menu_buscar.add(menuitem_buscar);

        jMenuBar1.add(menu_buscar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_musicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_musicasActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuitem_musicasActionPerformed

    private void menuitem_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_buscarActionPerformed
        // TODO add your handling code here:
         Interface_busca busca = new Interface_busca();
        jPanel3.add(busca);
        busca.setVisible(true);
    }//GEN-LAST:event_menuitem_buscarActionPerformed

    private void menuitem_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_playlistActionPerformed
        // TODO add your handling code here:
        Interface_playlist playlist = new Interface_playlist();
        
        playlist.setVisible(true);
        
    }//GEN-LAST:event_menuitem_playlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_online.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_online().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu menu_buscar;
    private javax.swing.JMenuItem menuitem_buscar;
    private javax.swing.JMenuItem menuitem_musicas;
    private javax.swing.JMenuItem menuitem_playlist;
    // End of variables declaration//GEN-END:variables
}
